const data = {
  questions: [
    {
      id: 1,
      category: 'HTML/CSS',
      text: "HTML стоит за 'Hyper Text Markup Language'.",
      answer: "Да",
      options: ["Да", "Нет"],
      recommendation: "HTML действительно означает 'Hyper Text Markup Language'.",
    },
    {
      id: 2,
      category: 'HTML/CSS',
      text: "CSS означает 'Cascading Style Sheets'.",
      answer: "Да",
      options: ["Да", "Нет"],
      recommendation: "CSS и правда расшифровывается как 'Cascading Style Sheets'.",
    },
    {
      id: 3,
      category: 'JavaScript',
      text: "JavaScript является статическим языком программирования.",
      answer: "Нет",
      options: ["Да", "Нет"],
      recommendation: "JavaScript является динамическим языком программирования.",
      
    },
    {
      id: 4,
      category: 'HTML/CSS',
      text: "Тег div является строчным элементом.",
      answer: "Нет",
      options: ["Да", "Нет"],
      recommendation: "Тег div является блочным элементом.",
    },
    {
      id: 5,
      category: 'HTML/CSS',
      text: "CSS может использоваться для стилизации HTML-элементов.",
      answer: "Да",
      options: ["Да", "Нет"],
      recommendation: "Да, CSS используется для стилизации HTML-элементов.",
      
    },
    {
      id: 6,
      category: 'JavaScript',
      text: "JavaScript может использоваться для добавления интерактивности на веб-страницу.",
      answer: "Да",
      options: ["Да", "Нет"],
      recommendation: "Да, JavaScript позволяет добавить интерактивность на веб-страницу.",
    },
    {
      id: 7,
      category: 'Web Development',
      text: "React - это библиотека для работы с базами данных.",
      answer: "Нет",
      options: ["Да", "Нет"],
      recommendation: "React предназначен для создания пользовательских интерфейсов, а не для работы с базами данных.",
    },
    {
      id: 8,
      category: 'HTML/CSS',
      text: "В HTML5 можно использовать тег canvas для рисования на веб-странице.",
      answer: "Да",
      options: ["Да", "Нет"],
      recommendation: "Да, с помощью тега canvas можно рисовать на веб-странице.",
    },
    {
      id: 9,
      category: 'JavaScript',
      text: "JavaScript можно использовать для работы с сервером.",
      answer: "Да",
      options: ["Да", "Нет"],
      recommendation: "Да, JavaScript может использоваться для взаимодействия с сервером.",
    },
    {
      id: 10,
      category: 'HTML/CSS',
      text: "CSS Grid - это технология для создания анимаций.",
      answer: "Нет",
      options: ["Да", "Нет"],
      recommendation: "CSS Grid предназначен для создания сеток, а не анимаций.",
    },
    {
      id: 11,
      category: 'Web Development',
      text: "RESTful API - это способ передачи звука через Интернет.",
      answer: "Нет",
      options: ["Да", "Нет"],
      recommendation: "RESTful API используется для создания веб-сервисов и передачи данных, а не звука.",
    },
    {
      id: 12,
      category: 'Web Development',
      text: "HTTP - это протокол для передачи гипертекста в сети Интернет.",
      answer: "Да",
      options: ["Да", "Нет"],
      recommendation: "Да, HTTP - это протокол для передачи гипертекста.",
    },
    {
      id: 13,
      category: 'Web Development',
      text: "JSON - это язык разметки для оформления текста.",
      answer: "Нет",
      options: ["Да", "Нет"],
      recommendation: "JSON - это формат обмена данными, а не язык разметки.",
    },
    {
      id: 14,
      category: 'Web Development',
      text: "React - это фреймворк для разработки мобильных приложений.",
      answer: "Нет",
      options: ["Да", "Нет"],
      recommendation: "React используется для создания пользовательских интерфейсов, включая веб-приложения, но не только мобильных.",
    },
    {
      id: 15,
      category: 'JavaScript',
      text: "Redux - это библиотека для управления состоянием приложения в React.",
      answer: "Да",
      options: ["Да", "Нет"],
      recommendation: "Да, Redux используется для управления состоянием приложения в React.",
    },
    {
      id: 16,
      category: 'Web Development',
      text: "Git - это система управления базами данных.",
      answer: "Нет",
      options: ["Да", "Нет"],
      recommendation: "Git - это система контроля версий, а не управления базами данных.",
    },
    {
      id: 17,
      category: 'JavaScript',
      text: "Node.js - это серверная среда для выполнения JavaScript на стороне сервера.",
      answer: "Да",
      options: ["Да", "Нет"],
      recommendation: "Да, Node.js позволяет выполнять JavaScript на сервере.",
    },
    {
      id: 18,
      category: 'JavaScript',
      text: "В JavaScript есть ключевое слово 'python'.",
      answer: "Нет",
      options: ["Да", "Нет"],
      recommendation: "В JavaScript нет ключевого слова 'python'.",
    },
    {
      id: 19,
      text: "CSS может использоваться для создания анимаций.",
      answer: "Да",
      options: ["Да", "Нет"],
      recommendation: "Да, CSS позволяет создавать анимации на веб-странице.",
    },
    {
      id: 20,
      category: 'HTML/CSS',
      text: "HTML - это язык программирования.",
      answer: "Нет",
      options: ["Да", "Нет"],
      recommendation: "HTML - это язык разметки, а не программирования.",
      id: 20,
    },
  ],
  categories: [ 
    { text: 'HTML/CSS', id: 1 },
    { text: 'JavaScript', id: 2 },
    { text: 'Web Development', id: 3}
  ],
};

module.exports = data;
